kind: Pod
apiVersion: v1
metadata:
        name: yamlsecret
spec:
   containers:
       - name: c01
         image: ubuntu
         command: ["/bin/bash","-c","while true; do echo This is cont 01; sleep 1000; done"]
    
         env:
          - name: MYENVUSER
            valueFrom:
               secretKeyRef:
                    name: myyamlsecret
                    key: myname

