kind: Pod
apiVersion: v1
metadata:
    name: mylivenessprobe
spec:
   containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash","-c","touch /tmp/myfile; sleep 10000"]

          livenessProbe:
               exec:
                  command:
                     - cat
                     - /tmp/myfile

               initialDelaySeconds: 5
               periodSeconds: 5
               timeoutSeconds: 30

