kind: PersistentVolume
apiVersion: v1
metadata:
    name: myebsvol

spec:
    capacity:
       storage: 1Gi
    accessModes:
       - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete      
    awsElasticBlockStore:
         volumeID: vol-0f78f9ae5a90cc704
         fsType: ext4
