kind: Pod
apiVersion: v1
metadata:
    name: nodelabeling
spec:
    containers:
         - name: c01
           image: ubuntu
           command: ["/bin/bash","-c","while true; do echo 'Hi Node labeling'; sleep 5; done"]
    nodeSelector:
          mynode: saidemy
