kind: Pod
apiVersion: v1
metadata:
    name: testpod2
    annotations:
        description: This is the description of pod
spec:
    containers:
        - name: c02
          image: ubuntu
          command: ["/bin/bash","-c","while true;do echo Hi Jinna; sleep 4; done"]
