kind: Pod
apiVersion: v1
metadata:
     name: testpod4
     annotations:
         description: This is an example of env var
spec:
     containers:
         - name: c01
           image: ubuntu
           command: ["/bin/bash","-c","while true; do echo 'Example of ENVs'; sleep 4; done"]

           env:
             - name: MYNAME
               value: jinu
