kind: Pod
apiVersion: v1
metadata:
    name: myreadness
spec:
   containers:
        - name: cont1
          image: httpd
          ports:
             - containerPort: 80

          readinessProbe:
              initialDelaySeconds: 10

              httpGet:
                 path: /
                 port: 80
